spring:
  jackson:
    default-property-inclusion: non_null
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: twitch
      client:
        config:
          twitch-api:
            url: https://api.twitch.tv/helix
            loggerLevel: basic
            default-request-headers:
              Client-Id: "xdfymjxgyywmn2gali84qokppxetpp"
  security:
    oauth2:
      client:
        registration:
          twitch:
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            client-id: "xdfymjxgyywmn2gali84qokppxetpp"
            client-secret: "wxutwpslj97vavd0fuifw0h2hm4jd5"
        provider:
          twitch:
            token-uri: https://id.twitch.tv/oauth2/token
  datasource:
    url: jdbc:mysql://${DATABASE_URL:localhost}:3306/twitch?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: "classpath:database-init.sql"

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: TRACE  # Incoming http requests
    com.laioffer.twitch.external.TwitchApiClient: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.jdbc.core: DEBUG  # SQL